alter table "public"."cities" drop constraint "cities_provinceid_fkey";

create table "public"."vehicle_makes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null
);


alter table "public"."vehicle_makes" enable row level security;

create table "public"."vehicle_models" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying,
    "vehicle_make_id" bigint,
    "vehicle_category_id" bigint
);


alter table "public"."vehicle_models" enable row level security;

create table "public"."vehicle_versions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "vehicle_model_id" bigint
);


alter table "public"."vehicle_versions" enable row level security;

alter table "public"."cities" drop column "provinceid";

alter table "public"."cities" add column "province_id" bigint not null;

CREATE UNIQUE INDEX vehicle_makes_pkey ON public.vehicle_makes USING btree (id);

CREATE UNIQUE INDEX vehicle_models_pkey ON public.vehicle_models USING btree (id);

CREATE UNIQUE INDEX vehicle_versions_pkey ON public.vehicle_versions USING btree (id);

alter table "public"."vehicle_makes" add constraint "vehicle_makes_pkey" PRIMARY KEY using index "vehicle_makes_pkey";

alter table "public"."vehicle_models" add constraint "vehicle_models_pkey" PRIMARY KEY using index "vehicle_models_pkey";

alter table "public"."vehicle_versions" add constraint "vehicle_versions_pkey" PRIMARY KEY using index "vehicle_versions_pkey";

alter table "public"."cities" add constraint "cities_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE not valid;

alter table "public"."cities" validate constraint "cities_province_id_fkey";

alter table "public"."vehicle_models" add constraint "vehicle_models_vehicle_category_id_fkey" FOREIGN KEY (vehicle_category_id) REFERENCES vehicle_categories(id) ON DELETE CASCADE not valid;

alter table "public"."vehicle_models" validate constraint "vehicle_models_vehicle_category_id_fkey";

alter table "public"."vehicle_models" add constraint "vehicle_models_vehicle_make_id_fkey" FOREIGN KEY (vehicle_make_id) REFERENCES vehicle_makes(id) ON DELETE CASCADE not valid;

alter table "public"."vehicle_models" validate constraint "vehicle_models_vehicle_make_id_fkey";

alter table "public"."vehicle_versions" add constraint "vehicle_versions_vehicle_model_id_fkey" FOREIGN KEY (vehicle_model_id) REFERENCES vehicle_models(id) ON DELETE CASCADE not valid;

alter table "public"."vehicle_versions" validate constraint "vehicle_versions_vehicle_model_id_fkey";

grant delete on table "public"."vehicle_makes" to "anon";

grant insert on table "public"."vehicle_makes" to "anon";

grant references on table "public"."vehicle_makes" to "anon";

grant select on table "public"."vehicle_makes" to "anon";

grant trigger on table "public"."vehicle_makes" to "anon";

grant truncate on table "public"."vehicle_makes" to "anon";

grant update on table "public"."vehicle_makes" to "anon";

grant delete on table "public"."vehicle_makes" to "authenticated";

grant insert on table "public"."vehicle_makes" to "authenticated";

grant references on table "public"."vehicle_makes" to "authenticated";

grant select on table "public"."vehicle_makes" to "authenticated";

grant trigger on table "public"."vehicle_makes" to "authenticated";

grant truncate on table "public"."vehicle_makes" to "authenticated";

grant update on table "public"."vehicle_makes" to "authenticated";

grant delete on table "public"."vehicle_makes" to "service_role";

grant insert on table "public"."vehicle_makes" to "service_role";

grant references on table "public"."vehicle_makes" to "service_role";

grant select on table "public"."vehicle_makes" to "service_role";

grant trigger on table "public"."vehicle_makes" to "service_role";

grant truncate on table "public"."vehicle_makes" to "service_role";

grant update on table "public"."vehicle_makes" to "service_role";

grant delete on table "public"."vehicle_models" to "anon";

grant insert on table "public"."vehicle_models" to "anon";

grant references on table "public"."vehicle_models" to "anon";

grant select on table "public"."vehicle_models" to "anon";

grant trigger on table "public"."vehicle_models" to "anon";

grant truncate on table "public"."vehicle_models" to "anon";

grant update on table "public"."vehicle_models" to "anon";

grant delete on table "public"."vehicle_models" to "authenticated";

grant insert on table "public"."vehicle_models" to "authenticated";

grant references on table "public"."vehicle_models" to "authenticated";

grant select on table "public"."vehicle_models" to "authenticated";

grant trigger on table "public"."vehicle_models" to "authenticated";

grant truncate on table "public"."vehicle_models" to "authenticated";

grant update on table "public"."vehicle_models" to "authenticated";

grant delete on table "public"."vehicle_models" to "service_role";

grant insert on table "public"."vehicle_models" to "service_role";

grant references on table "public"."vehicle_models" to "service_role";

grant select on table "public"."vehicle_models" to "service_role";

grant trigger on table "public"."vehicle_models" to "service_role";

grant truncate on table "public"."vehicle_models" to "service_role";

grant update on table "public"."vehicle_models" to "service_role";

grant delete on table "public"."vehicle_versions" to "anon";

grant insert on table "public"."vehicle_versions" to "anon";

grant references on table "public"."vehicle_versions" to "anon";

grant select on table "public"."vehicle_versions" to "anon";

grant trigger on table "public"."vehicle_versions" to "anon";

grant truncate on table "public"."vehicle_versions" to "anon";

grant update on table "public"."vehicle_versions" to "anon";

grant delete on table "public"."vehicle_versions" to "authenticated";

grant insert on table "public"."vehicle_versions" to "authenticated";

grant references on table "public"."vehicle_versions" to "authenticated";

grant select on table "public"."vehicle_versions" to "authenticated";

grant trigger on table "public"."vehicle_versions" to "authenticated";

grant truncate on table "public"."vehicle_versions" to "authenticated";

grant update on table "public"."vehicle_versions" to "authenticated";

grant delete on table "public"."vehicle_versions" to "service_role";

grant insert on table "public"."vehicle_versions" to "service_role";

grant references on table "public"."vehicle_versions" to "service_role";

grant select on table "public"."vehicle_versions" to "service_role";

grant trigger on table "public"."vehicle_versions" to "service_role";

grant truncate on table "public"."vehicle_versions" to "service_role";

grant update on table "public"."vehicle_versions" to "service_role";


